site_name: Robin's Blog


theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  icon:
    repo: fontawesome/brands/github
  logo: 'assets/logo_white.png'
  favicon: 'assets/favicon.ico'


extra:
  search:
    language: 'zh'


repo_url: https://github.com/robinoneway/MkDocs
repo_name: Robin's Blog

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets